
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes: ["ollama:/root/.ollama"]
    ports: ["11434:11434"]
    environment:
      - OLLAMA_MAX_LOADED_MODELS=2

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes: ["qdrant:/qdrant/storage"]
    ports: ["6333:6333"]

  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ingres
    ports: ["5432:5432"]
    volumes: 
      - "pg:/var/lib/postgresql/data"
      - "./init-db:/docker-entrypoint-initdb.d"
    command: ["postgres", "-c", "log_statement=all"]

  api:
    build: ./app
    depends_on: [ollama, qdrant, postgres]
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - PG_URI=postgresql+psycopg://postgres:postgres@postgres:5432/ingres
    ports: ["8000:8000"]
    volumes: ["./data:/app/data"]

  ui:
    build: ./ui
    depends_on: [api]
    ports: ["8501:8501"]
    environment:
      - API_URL=http://api:8000

volumes: { ollama: {}, qdrant: {}, pg: {} }
